stroy_magaz/others/urls.py
from django.urls import path, include
from .views import *

app_name = 'faq'

urlpatterns = [
    path('', ListFaq.as_view(), name='list_faq_url'),
]

stroy_magaz/portfolio/urls.py
from django.urls import path, include
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('object/<slug>', DetailPortfolioObj.as_view(), name='p_obj_detail_url'),
    path('topic/<slug>', ListTopcDetail.as_view(), name='list_p_obj_topic_url'),
    path('', ListAllPortfolio.as_view(), name='list_all_portfolio'),
    ]

stroy_magaz/stroy_magaz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from .home_views import HomeList
from others.views import add_coll_back, add_comment, create_order, AboutUsPage, Contact, MainCommentsView, CollBackView, CollBackSuccessView, OrderCreateView, OrderCreateSuccessView, DocumentationsView
from portfolio.views import ListAllPortfolio
from site_some_settings.views import SearchView

#


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    path('about-us/', AboutUsPage.as_view(), name='about_us_url'),
    path('documentations/', DocumentationsView.as_view(), name='documentations_url'),
    path('portfolioobject/', ListAllPortfolio.as_view(), name='dfghfgds'),

    path('add-comment/', add_comment, name='add_comment_url'),
    path('create-order/', create_order, name='create_order_url'),

    path('search/', SearchView.as_view(), name='search_url'),

    path('coll-back/', CollBackView.as_view(), name='coll_bacl_form_url'),
    path('add-coll-back/', add_coll_back, name='add_coll_bacl_url'),
    path('coll-back/success/', CollBackSuccessView.as_view(), name='coll_bacl_success_url'),

    path('order-create/', OrderCreateView.as_view(), name='order_create_form_url'),
    path('order-create/success/', OrderCreateSuccessView.as_view(), name='order_create_success_url'),

    path('contacts/', Contact.as_view(), name='contacts_url'),


    path('comments/', MainCommentsView.as_view(), name='main_comments_url'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('test/', include('ticket.urls')),
    path('faq/', include('others.urls', namespace='faq')),

    path('portfolio', include('portfolio.urls', namespace='portfolio')),
    path('admin-detail/', include('site_some_settings.urls', namespace='admin_detail')),

    re_path(r'^$', HomeList.as_view(), name='home_url'),
    path('', include('service.urls', namespace='service')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stroy_magaz/templates/kind_works&service/includes/detail_services_of_kind_work.html
{% load static %}
{% if service_kind_works %}

    <h2>Предоставлямые виды работы</h2>

    {% for service in service_kind_works%}
        <div class="col-xl-4 col-md-6 col-xs-12">
            <div class="item item-left">
                <figure class="item-thumb">
                    <!--555x350-->
                    {% if service.main_image %}<a href="{{ service.get_absolute_url }}"><img src="{{ service.main_image.url }}" style="height: 200px; width: 300px" alt=""></a>{% else %}<img src="{% static 'images/not-image.jpg' %}" style="height: 200px; width: 300px" class="example_beauty" />{% endif %}
                </figure>
                <div class="item-content">
                    <p class="item-title"><a href="{{ service.get_absolute_url }}">{{ service.name }}</a></p>
{#                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, alias aliquam amet aperiam consequuntur deleniti doloribus eaque eum excepturi fugit libero, odio omnis perferendis perspiciatis sunt temporibus totam, vel vero!</p>#}
                </div>
            </div>
                </div>
    {% endfor %}

{% endif %}

stroy_magaz/templates/kind_works&service/includes/gallery_kind_works.html
{% if kind_work.get_list_images and kind_work.gallery_availability%}

    <main class="main">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">

                    <div class="page-hero">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h1 class="page-title">Галерея</h1>
                                    <p class="page-subtitle">Раздел: {{ kind_work.name }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row row-equal row-items">
                        {% for image in kind_work.get_list_images %}
                            <div class="col-md-3 col-xs-12">
                                <div class="item item-left">
                                    <figure class="item-thumb">
                                        <a href="{{ image.image.url }}"  target="_blank"><img src="{{ image.image.url }}" style="height: 200px; width: 300px" alt=""></a>
                                    </figure>
                                    <div class="item-content">

                                        <p class="item-title">
                                            <a href="{{ image.image.url }}"  target="_blank"">
                                                {{ image.name }}
                                            </a>
                                        </p>
                                        {% if image.description %}
                                            <p>{{ image.description }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </main>


{% endif %}

stroy_magaz/templates/kind_works&service/includes/gallery_services.html
{% if service.get_list_images and service.gallery_availability %}

    <main class="main">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">

                    <div class="page-hero">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h1 class="page-title">Галерея</h1>
                                    <p class="page-subtitle">Раздел: {{ service.name }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row row-equal row-items">
                        {% for image in service.get_list_images %}
                            <div class="col-md-3 col-xs-12">
                                <div class="item item-left">
                                    <figure class="item-thumb">
                                        <a href="{{ image.image.url }}"  target="_blank"><img src="{{ image.image.url }}" style="height: 200px; width: 300px" alt=""></a>
                                    </figure>
                                    <div class="item-content">

                                        <p class="item-title">
                                            <a href="">
                                                {{ image.name }}
                                            </a>
                                        </p>
                                        {% if image.description %}
                                            <p>{{ image.description }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </main>


{% endif %}

stroy_magaz/templates/kind_works&service/includes/kind_wokr_comments.html
<main class="main">
    <div class="container">
        <div class="row">
                <article class="entry"id="form-wrapper" id="form-wrapper">
                    <div id="comments">
                        <div class="post-comments">
                            <div class="widget widget_ci-clients widget-padded">
                                <div style="background-color: #362F2D; color: #fff;" class="col-xl-12 col-lg-12 col-xs-12 widget_about">
                                    <div class="col-xl-6 col-lg-6 col-xs-12" style="margin-top: 50px">

                                        <h2>
                                            Обсуждение
                                        </h2><br><br>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-xs-12" align="right" style="margin-top: 40px">
                                        <a href="#add-comment" class="btn btn-lg">Добавить свой коментарий<i class="fa fa-caret-right"></i></a>

                                    </div>
                                </div>
                            </div>
                            {% if comments %}
                                <div class="col-xl-12 col-lg-12 col-xs-12">
                                <ol id="comment-list">
                                    <li class="comment bypostauthor">
                                        <br><br>
                                        {% for comment in comments %}
                                            {% if comment.moderation or site_settings.confirm_services_comments %}
                                                <article class="comment-body">
                                                    <footer class="comment-meta">
                                                        <div class="comment-metadata">
                                                            <time datetime="{{ comment.created}}">
                                                                <span>{{ comment.created|date:"d-m-Y" }}</span>
                                                                <span style="margin-left: 40px">
                                                                    модерация:
                                                                    {% if comment.moderation %}
                                                                        ПРОЙДЕНА
                                                                    {% else %}
                                                                        НЕ ПРОЙДЕНА
                                                                    {% endif %}
                                                                </span>
                                                            </time>
                                                            <span><h5 style="margin-top: 5px"><span style="text-transform: lowercase;">автор:</span> <span style="margin-left: 20px">{{ comment.name_person }}</span></h5></span>
{#                                                            <span style="margin-left: 0px" class="comment-reply-link">{{ comment.kind_job }}</span>#}
{#                                                            <span class="comment-reply-link">Оценка: {{ comment.job_satisfaction }}</span>#}

                                                        </div>
                                                        <span style="margin-left: 40px; background: #fdffd7" > {{ comment.comment_body }}</span>
                                                    </footer>

                                                    <!-- .comment-content -->
    {#                                                <div class="reply"> <a class="comment-reply-link" href="#respond">Reply</a> </div>#}
                                                    <!-- .reply -->
                                                <br><hr><br>
                                                </article>
                                            {% endif %}
                                        {% endfor %}
                            {% else %}
                                <div class="col-xl-12 col-lg-12 col-xs-12">
                                    <br><br><h2>Никто еще не написал коментария</h2><br><br>
                                </div>
                            {% endif %}



                        <!-- .post-comments -->
                        <br><br><br>
                        <section>
                            <div id="add-comment" class="group">
                                <div id="respond" class="comment-respond">



{#                                    <form action="{% url 'portfolio:p_obj_detail_url' slug=p_obj.slug%}" method="post" id="commentform" class="comment-form" novalidate="" >#}
                                    <form action="{{ p_ojb.get_absoulute_url }}" method="post" id="commentform" class="comment-form" novalidate="" >
                                        <div class="col-xl-12 col-lg-4 col-xs-4">
                                            <h3>
                                                Добавить коментарий
                                            </h3>
                                            <p class="comment-notes">Ваш адрес электронной почты не будет опубликован. Обязательные поля помечены <span class="required">*</span> </p>
                                        </div>


                                        <div class="col-xl-6 col-lg-4 col-xs-4">
                                            <h3 style="color: #702000">{{ comment_form.name_person.errors }}</h3>
                                            <b>{{ comment_form.name_person.label }}</b>
                                            {{ comment_form.name_person }}
                                        </div>
                                        <div class="col-xl-6 col-lg-12 col-xs-12">
                                            <h3 style="color: #702000">{{ comment_form.email.errors }}</h3>
                                            <b>{{ comment_form.email.label }}</b>
                                            {{ comment_form.email }}
                                        </div>


                                        <div class="col-xl-12 col-lg-12 col-xs-12">
                                            <h3 style="color: #702000">{{ comment_form.comment_body.errors }}</h3>
                                            <br><b>{{ comment_form.comment_body.label }}</b>
                                            {{ comment_form.comment_body }}
                                        </div>




                                        <div class="col-xl-12 col-lg-12 col-xs-12">
                                            <br><br>
                                            {% if not site_settings.confirm_services_comments %}
                                                <p class="form-allowed-tags"> Ваш коментарий будет опубликован после проверки администратора</p>
                                            {% endif %}
                                            {% csrf_token %}
{#                                            <h1>{{ p_obj.id }}</h1>#}
                                            <p class="form-submit"> <input name="submit" type="submit" id="submit" value="Отправить коментарий"> </p>
                                        </div>
                                    </form>
                                </div>
                                <!-- #respond -->
                            </div>
                            <!-- #form-wrapper -->
                        </section>
                    </div>
                </article>
            </div>
        </div>
    </div>
</main>

stroy_magaz/templates/kind_works&service/includes/right_column.html
<div class="col-xl-3 col-lg-4 col-xs-12">
    <div class="sidebar">

        {% include 'components/order_create_form.html' %}
        {% if request.path != '/kind-works/'%}
            {% include 'components/add_comment-button.html' %}
        {% endif %}
        <aside class="widget widget_categories group">
            {% include 'kind_works&service/includes/include/list_service.html' %}
        </aside>

    </div>
</div>