stroy_magaz/others/urls.py
from django.urls import path, include
from .views import *

app_name = 'faq'

urlpatterns = [
    path('', ListFaq.as_view(), name='list_faq_url'),
]

stroy_magaz/service/urls.py
from django.urls import path, include
from .views import *

app_name = 'service'

urlpatterns = [
    path('kind-works/service/<slug>', ServiceDetail.as_view(), name='service_detail_url'),
    path('kind-works/<slug>', DetailKindWork.as_view(), name='kind_works_detail_url'),
    path('kind-works/', ListKindWork.as_view(), name='kind_works_list_url'),
    # path('', HomeList.as_view(), name='home_url'),
]

stroy_magaz/stroy_magaz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from .home_views import HomeList
from others.views import add_coll_back, add_comment, create_order, AboutUsPage, Contact, MainCommentsView, CollBackView, CollBackSuccessView, OrderCreateView, OrderCreateSuccessView, DocumentationsView
from portfolio.views import ListAllPortfolio
from site_some_settings.views import SearchView

#


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    path('about-us/', AboutUsPage.as_view(), name='about_us_url'),
    path('documentations/', DocumentationsView.as_view(), name='documentations_url'),
    path('portfolioobject/', ListAllPortfolio.as_view(), name='dfghfgds'),

    path('add-comment/', add_comment, name='add_comment_url'),
    path('create-order/', create_order, name='create_order_url'),

    path('search/', SearchView.as_view(), name='search_url'),

    path('coll-back/', CollBackView.as_view(), name='coll_bacl_form_url'),
    path('add-coll-back/', add_coll_back, name='add_coll_bacl_url'),
    path('coll-back/success/', CollBackSuccessView.as_view(), name='coll_bacl_success_url'),

    path('order-create/', OrderCreateView.as_view(), name='order_create_form_url'),
    path('order-create/success/', OrderCreateSuccessView.as_view(), name='order_create_success_url'),

    path('contacts/', Contact.as_view(), name='contacts_url'),


    path('comments/', MainCommentsView.as_view(), name='main_comments_url'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('test/', include('ticket.urls')),
    path('faq/', include('others.urls', namespace='faq')),

    path('portfolio', include('portfolio.urls', namespace='portfolio')),
    path('admin-detail/', include('site_some_settings.urls', namespace='admin_detail')),

    re_path(r'^$', HomeList.as_view(), name='home_url'),
    path('', include('service.urls', namespace='service')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stroy_magaz/templates/kind_works&service/kind_works_detail.html
<style>
    .border {
        list-style: none;
        padding: 0;
    }
    .border li {
        font-family: "Trebuchet MS", "Lucida Sans";
        padding: 7px 20px;
        margin-bottom: 10px;
        border-radius: 5px;
        border-left: 10px solid #f05d22;
        box-shadow: 2px -2px 5px 0 rgba(0,0,0,.1),
        -2px -2px 5px 0 rgba(0,0,0,.1),
        2px 2px 5px 0 rgba(0,0,0,.1),
        -2px 2px 5px 0 rgba(0,0,0,.1);
        font-size: 20px;
        letter-spacing: 2px;
        transition: 0.3s all linear;
    }
    .border li:nth-child(2){border-color: #8bc63e;}
    .border li:nth-child(3){border-color: #fcba30;}
    .border li:nth-child(4){border-color: #1ccfc9;}
    .border li:nth-child(5){border-color: #493224;}
    .border li:hover {border-left: 10px solid transparent;}
    .border li:nth-child(1):hover {border-right: 10px solid #f05d22;}
    .border li:nth-child(2):hover {border-right: 10px solid #8bc63e;}
    .border li:nth-child(3):hover {border-right: 10px solid #fcba30;}
    .border li:nth-child(4):hover {border-right: 10px solid #1ccfc9;}
    .border li:nth-child(5):hover {border-right: 10px solid #493224;}
</style>
{% extends 'base.html' %}
{% load static %}

{%  block title %}

    {% if site_settings.site_name %}
        {{ kind_work.name }} |{{ site_settings.site_name  }}|
    {% else %}
        {{ kind_work.name }}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="page-hero">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-title">{{ kind_work.name }}</h2>
                    <p class="page-subtitle">
                        {% if kind_work.intro %}
                            {{ kind_work.intro }}
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>

    <main class="main">
        <div class="container">
        <p class="page-subtitle">
            <div class="entry-meta">
                <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                <p class="entry-meta-item entry-comments-link"><a href="{% url 'service:kind_works_list_url' %}">Все услуги</a></p>
                <p class="entry-meta-item entry-comments-link">{{ kind_work }}</p>
            </div>
        </p>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-xs-12">
                    <article class="entry">
                        {% if kind_work.desctiption %}
                            {{ kind_work.desctiption|safe }}
                        {% else %}
                            <h4>Описание данной статьи еще не готово.</h4>
                            Для получение подробностей свяжитесь с нами.
                        {% endif %}


                        <br><br><hr>

                        {% if service_kind_works %}
                            <h2 align="center">СТОИМОСТЬ РАБОТ</h2>
                            <table>
                                <thead>
                                    <tr>
                                        <th>НАИМЕНОВАНИЕ РАБОТ</th>
                                        <th>ЦЕНА руб.</th>
                                        <th>ЕД. ИЗМ.</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for service in service_kind_works %}

                                        <tr>
                                            <th align="center"><a href="{{ service.get_absolute_url }}" style="color: chocolate">{{ service.name }}</a></th>
                                            <td align="center">
                                                {% if service.price %}
                                                    {{ service.price }}
                                                {% else %}
                                                    договорная
                                                {% endif %}
                                            </td>
                                            <td align="center">
                                                {% if service.price  %}
                                                    {% if service.unit  %}
                                                        {{ service.unit }}
                                                    {% else %}

                                                    {% endif %}
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                             <hr>
                        {% endif %}



                    <br><br><br>
                    {% include 'kind_works&service/includes/detail_services_of_kind_work.html' %}

                    </article>
                </div>

                {% include 'kind_works&service/includes/right_column.html' %}

            </div>
        </div>
    </main>
    {% include 'kind_works&service/includes/gallery_kind_works.html' %}

    {% include 'kind_works&service/includes/kind_wokr_comments.html' %}


{% endblock %}

stroy_magaz/templates/kind_works&service/list_kind_works.html
{% extends 'base.html' %}
{% load static %}


{%  block title %}

    {% if site_settings.site_name %}
        Все услуги |{{ site_settings.site_name  }}|
    {% else %}
        Все услуги
    {% endif %}
{% endblock %}
{% block content %}
    <div class="page-hero">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-title">Предоставляемые услуги</h2>
                </div>
            </div>
        </div>
    </div>
    {{ dds }}
    <br>
    dd | {{ dfgh.ddddc }}
    <br>
    <main class="main">
        <div class="container">
        <p class="page-subtitle">
            <div class="entry-meta">
                <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                <p class="entry-meta-item entry-comments-link">Все услуги</p>
            </div>
        </p>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-xs-12">
                    <article class="entry">

                          {% if kindworks %}
                             <div class="row row-equal row-items">

                                {% for kindwork in kindworks %}

                                    <div class="col-md-6 col-xs-12">
                                        <div class="item item-left">
                                            <figure class="item-thumb">
                                                <div style="position: relative">
                                                    <a href="{{ kindwork.get_absolute_url }}">
                                                        <div class="imagetext">
                                                            {% if kindwork.main_image %}<img src="{{ kindwork.main_image.url }}" style="height: 350px; width: 400px" class="example_beauty" />{% else %}<img src="{% static 'images/not-image.jpg' %}" style="height: 350px; width: 450px" class="example_beauty" />{% endif %}

                                                        <div class="for_text">
                                                            <div align="center">
                                                                <div class="btn btn-lg">
                                                                 {{ kindwork.name }}<i class="fa fa-caret-right"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            </figure>

                                        </div>
                                    </div>

                                {% endfor %}

                            </div>
                        {% else %}
                            <div class="col-xl-12 col-md-12 col-xs-12">
                                <div align="center">
                                    <figure class="entry-thumb">
                                        <span align="center"><img align="center" src="{% static 'images/non-page.png' %}" alt=""> </span>
                                    </figure>
                                </div>

                            </div>

                        {% endif %}

                    </article>
                </div>

                {% include 'kind_works&service/includes/right_column.html' %}

            </div>
        </div>
    </main>

{% endblock %}

stroy_magaz/templates/kind_works&service/service_deail.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}

    {% if site_settings.site_name %}
        {{ service.name }}: {{ site_settings.site_name  }}
    {% else %}
        {{ service.name }}
    {% endif %}
{% endblock %}

{% block content %}

    <div class="page-hero">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-title">{{ service.name }}</h2>

                </div>
            </div>
        </div>
    </div>


    <main class="main">
        <div class="container">
            <p class="page-subtitle">
                <div class="entry-meta">
                    <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                    <p class="entry-meta-item entry-comments-link"><a href="{% url 'service:kind_works_list_url' %}">Все услуги</a></p>
                    <p class="entry-meta-item entry-comments-link"><a href="{{ kind_work.get_absolute_url }}">{{ kind_work }}</a></p>
                    <p class="entry-meta-item entry-comments-link">{{ service }}</p>
                </div>
            </p>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-xs-12">
                    <article class="entry">
                        {% if service.desctiptions %}
                            {{ service.desctiptions|safe }}
                        {% else %}
                            <h4>Описание данной статьи еще не готово.</h4>
                            Для получение подробностей свяжитесь с нами.
                        {% endif %}

                    </article>
                </div>

                {% include 'kind_works&service/includes/right_column.html' %}



            </div>
        </div>
    </main>
    {% include  'kind_works&service/includes/gallery_services.html' %}

    {% include 'kind_works&service/includes/kind_wokr_comments.html' %}


{% endblock %}