stroy_magaz/others/urls.py
from django.urls import path, include
from .views import *

app_name = 'faq'

urlpatterns = [
    path('', ListFaq.as_view(), name='list_faq_url'),
]

stroy_magaz/portfolio/urls.py
from django.urls import path, include
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('object/<slug>', DetailPortfolioObj.as_view(), name='p_obj_detail_url'),
    path('topic/<slug>', ListTopcDetail.as_view(), name='list_p_obj_topic_url'),
    path('', ListAllPortfolio.as_view(), name='list_all_portfolio'),
    ]

stroy_magaz/stroy_magaz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from .home_views import HomeList
from others.views import add_coll_back, add_comment, create_order, AboutUsPage, Contact, MainCommentsView, CollBackView, CollBackSuccessView, OrderCreateView, OrderCreateSuccessView, DocumentationsView
from portfolio.views import ListAllPortfolio
from site_some_settings.views import SearchView

#


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    path('about-us/', AboutUsPage.as_view(), name='about_us_url'),
    path('documentations/', DocumentationsView.as_view(), name='documentations_url'),
    path('portfolioobject/', ListAllPortfolio.as_view(), name='dfghfgds'),

    path('add-comment/', add_comment, name='add_comment_url'),
    path('create-order/', create_order, name='create_order_url'),

    path('search/', SearchView.as_view(), name='search_url'),

    path('coll-back/', CollBackView.as_view(), name='coll_bacl_form_url'),
    path('add-coll-back/', add_coll_back, name='add_coll_bacl_url'),
    path('coll-back/success/', CollBackSuccessView.as_view(), name='coll_bacl_success_url'),

    path('order-create/', OrderCreateView.as_view(), name='order_create_form_url'),
    path('order-create/success/', OrderCreateSuccessView.as_view(), name='order_create_success_url'),

    path('contacts/', Contact.as_view(), name='contacts_url'),


    path('comments/', MainCommentsView.as_view(), name='main_comments_url'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('test/', include('ticket.urls')),
    path('faq/', include('others.urls', namespace='faq')),

    path('portfolio', include('portfolio.urls', namespace='portfolio')),
    path('admin-detail/', include('site_some_settings.urls', namespace='admin_detail')),

    re_path(r'^$', HomeList.as_view(), name='home_url'),
    path('', include('service.urls', namespace='service')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stroy_magaz/portfolio/models/comments.py
from django.db import models
from .portfolio import Portfolio



class PortfolioComments(models.Model):
    """Модель Коментариев для объектов портфолио"""

    class Meta:
        ordering = ('-updated',)
        verbose_name = 'Коментарии объектов портфолио'
        verbose_name_plural = 'Коментарии объектов портфолио'

    parent_object = models.IntegerField(blank=True, null=True, verbose_name='ID Объектa коментирования')
    name_person = models.CharField(max_length=200, verbose_name='Имя того кто написал коментарий')
    email = models.CharField(max_length=200, verbose_name='Email')
    comment_body = models.TextField(verbose_name='Тело коментария')


    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    moderation = models.BooleanField(default=False, verbose_name='Модерация')
    watched = models.BooleanField(default=False, verbose_name='Просмотрено')

    # def get_absolte_url(self):
    #     return reverse('portfolio:p_obj_detail_url', args=[self.parent_object])

    def __str__(self):
        # return 'описание: {}'.format(self.descriptions)
        return self.name_person

    def obj_name(self):
        if self.parent_object:
            p_obj = Portfolio.objects.get(id=self.parent_object)
            from django.utils.safestring import mark_safe
            return mark_safe(u'{}'.format(p_obj.name))
        else:
            return '(Нет id)'

    obj_name.short_description = 'Объект коментирования'
    obj_name.allow_tags = True

stroy_magaz/portfolio/models/images.py
from django.db import models
from datetime import datetime


def generate_filename(instance, filename):
    filename = instance.slug + '.jpg'
    year = datetime.now().year
    month = datetime.now().month
    return 'portfolio/gallary/{0}/month-{1}/{2}'.format(year, month, filename)



class Images(models.Model):
    """Общая галлерея изображений для портфолио"""

    class Meta:
        ordering = ('image',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Общая галлерея изображений для портфолио'
        verbose_name_plural = '1. Общая галлерея изображений для портфолио'

    image = models.ImageField(upload_to=generate_filename, verbose_name='Все изображения приложения услуги')
    name = models.CharField(max_length=200,  unique=True, verbose_name='Наименование')
    description = models.CharField(max_length=800,  blank=True, null=True, verbose_name='Описаниее')
    slug = models.SlugField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')


    def image_img(self):
        if self.image:
            from django.utils.safestring import mark_safe
            return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(self.image.url))
        else:
            return '(Нет изображения)'

    image_img.short_description = 'Картинка'
    image_img.allow_tags = True

    def __str__(self):
        # return 'описание: {}'.format(self.descriptions)
        return self.name

stroy_magaz/portfolio/models/portfolio.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from .images import Images



class Topic(models.Model):
    """Категории раздела портфолио"""

    class Meta:
        verbose_name = 'Категории раздела портфолио'
        verbose_name_plural = '2. Категории раздела портфолио'

    name = models.CharField(max_length=200, verbose_name='Названи категории')
    slug = models.SlugField()
    descriprion = RichTextUploadingField(blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('portfolio:list_p_obj_topic_url', args=[self.slug])



from datetime import datetime
def generate_filename(instance, filename):
    filename = instance.slug + '.jpg'
    year = datetime.now().year
    month = datetime.now().month
    return 'portfolio/p-obj-main-image/{0}/month-{1}/{2}'.format(year, month, filename)



class Portfolio(models.Model):
    """Оъекты раздела портфолио"""

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Портфолио'
        verbose_name_plural = '3. Объекты портфолио'

    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING, verbose_name='Категория')
    name = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField()
    description = RichTextUploadingField(blank=True, null=True, verbose_name='Описание')
    main_image = models.ImageField(upload_to=generate_filename, verbose_name='Главное изображение')
    images = models.ManyToManyField(Images, blank=True, verbose_name='Галерея изображений')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    availability = models.BooleanField(default=True,
                                               verbose_name='Отображать на сайте')


    def get_absolute_url(self):
        return reverse('portfolio:p_obj_detail_url', args=[self.slug])


    def get_list_images(self):
        list = self.images.get_queryset()
        return list




    def __str__(self):
        return self.name

    def image_img(self):
        if self.main_image:
            from django.utils.safestring import mark_safe
            return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(self.main_image.url))
        else:
            return '(Нет изображения)'

    image_img.short_description = 'Картинка'
    image_img.allow_tags = True

    def obj_id(self):
        if self.id:
            from django.utils.safestring import mark_safe
            return mark_safe(u'{}'.format(self.id))
        else:
            return '(Нет id)'

    obj_id.short_description = 'ID объекта'
    obj_id.allow_tags = True

stroy_magaz/portfolio/forms.py
from django import forms
from .models.comments import PortfolioComments

class PortfolioCommentsForm(forms.ModelForm):
    """Форма добавления коментариев в разделе портфолио"""

    name_person = forms.CharField(label='* ФИО / Название компании', error_messages={
        'required': 'Данное поле обязательно к заполнение. Пожалуйста введите данные корректно.',
        'invalid': 'Введите данные корректно!'},
                                  required=True, widget=forms.TextInput(
            attrs={'placeholder': '** Ваше полное имя / Название компании'}))

    email = forms.EmailField(label='* Ваш Email', error_messages={'invalid': 'Введите email корректно!',
                                                                         'required': 'Это поле обязательно. '}, )

    comment_body = forms.CharField(label='* Коментарий',
                                         error_messages={'required': 'Это поле обязательно. ', 'invalid': 'Введите данные корректно!'},
                                         required=True,
                                         widget=forms.Textarea(
                                             attrs={'type': 'text',
                                                    'placeholder': '** Ваш коментарий'}))


    class Meta(object):
        model = PortfolioComments
        fields = ['name_person', 'email', 'comment_body', 'parent_object']

stroy_magaz/portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models.portfolio import Portfolio, Topic
from .models.comments import PortfolioComments

from service.models.kindworks import KindWorks
from others.models.about_us import AboutUs
from others.models.documentation import Documentation
from site_some_settings.models import SiteSettings
from site_some_settings.mixins import KindWorkMixin
from .forms import PortfolioCommentsForm
from .tasks import mail_sent_create_portfolio_comment




class ListAllPortfolio(ListView, KindWorkMixin):
    """Отображение всех объектов портфолио"""

    model = Portfolio
    template_name = 'portfolio/list_all_portfolio.html'

    def get_context_data(self, *args, **kwargs):
        data = super(ListAllPortfolio, self).get_context_data(*args, **kwargs)
        data['p_objects'] = self.model.objects.all()
        data['topics'] = Topic.objects.all()


        return data




class ListTopcDetail(DetailView, KindWorkMixin):
    """Отображение объектов портфолио относящихся к выбранной категории"""

    model = Topic
    template_name = 'portfolio/list_topic_portfolio.html'

    def get_context_data(self, *args, **kwargs):
        data = super(ListTopcDetail, self).get_context_data(*args, **kwargs)
        data['topic'] = self.get_object()
        data['topics'] = Topic.objects.all()
        data['p_objects'] = Portfolio.objects.filter(topic_id=data['topic'].id)

        return data



class DetailPortfolioObj(DetailView, KindWorkMixin):
    """Отображает конкретный объект портфолио и обрабатывает коментарии к нему"""

    model = Portfolio
    template_name = 'portfolio/p_obj_detail.html'

    def get_context_data(self, *args, **kwargs):
        data = super(DetailPortfolioObj, self).get_context_data(*args, **kwargs)
        data['p_obj'] = self.get_object()
        data['topics'] = Topic.objects.all()

        #получаю категорию к коткоторой относиться объект
        data['topic'] = Topic.objects.get(id=self.get_object().topic_id)

        # получаю queryset коментариев относящихся к этому объекту
        data['comments'] = PortfolioComments.objects.filter(parent_object=self.get_object().id)

        data['comment_form'] = PortfolioCommentsForm()


        return data


    def post(self, request, *args, **kwargs):

        p_obj = self.get_object()

        if request.method == 'POST':
            comment_form = PortfolioCommentsForm(request.POST)
            if comment_form.is_valid():
                comment_form.save(commit=False)
                instance = comment_form.instance
                instance.parent_object = p_obj.id

                comment = comment_form.save()


                """Подготовка данных к отправке и отправка емейла клиенту и админу"""
                info = []
                info.extend((comment.parent_object, comment.name_person, comment.email, comment.comment_body))
                info.append((HttpRequest.get_host(request) + '/portfolioobject/' + str(p_obj.slug) + '#form-wrapper'))
                info.append((HttpRequest.get_host(request) + '/admin/portfolio/portfoliocomments/' + str(comment.id) + '/change/'))
                # print(info)
                mail_sent_create_portfolio_comment.delay(info)



                return redirect('/portfolioobject/' + str(p_obj.slug) + '#form-wrapper')
        else:
            comment_form = PortfolioCommentsForm()

        site_settings = SiteSettings.objects.first()
        kindworks = KindWorks.objects.all()
        about_us = AboutUs.objects.first()
        documentations = Documentation.objects.all()

        context = {
            'comment_form':comment_form,
            'documentations': documentations,
            'about_us': about_us,
            'site_settings': site_settings,
            'kindworks': kindworks,
                   }

        return render(request, 'portfolio/p_obj_detail.html', context=context)

stroy_magaz/templates/portfolio/list_all_portfolio.html
<style>
    .border {
        list-style: none;
        padding: 0;
    }
    .border li {
        font-family: "Trebuchet MS", "Lucida Sans";
        padding: 7px 20px;
        margin-bottom: 10px;
        border-radius: 5px;
        border-left: 10px solid #f05d22;
        box-shadow: 2px -2px 5px 0 rgba(0,0,0,.1),
        -2px -2px 5px 0 rgba(0,0,0,.1),
        2px 2px 5px 0 rgba(0,0,0,.1),
        -2px 2px 5px 0 rgba(0,0,0,.1);
        font-size: 20px;
        letter-spacing: 2px;
        transition: 0.3s all linear;
    }
    .border li:nth-child(2){border-color: #8bc63e;}
    .border li:nth-child(3){border-color: #fcba30;}
    .border li:nth-child(4){border-color: #1ccfc9;}
    .border li:nth-child(5){border-color: #493224;}
    .border li:hover {border-left: 10px solid transparent;}
    .border li:nth-child(1):hover {border-right: 10px solid #f05d22;}
    .border li:nth-child(2):hover {border-right: 10px solid #8bc63e;}
    .border li:nth-child(3):hover {border-right: 10px solid #fcba30;}
    .border li:nth-child(4):hover {border-right: 10px solid #1ccfc9;}
    .border li:nth-child(5):hover {border-right: 10px solid #493224;}
</style>
{% extends 'base.html' %}
{% load static %}


{%  block title %}

    {% if site_settings.site_name %}
        Портфолио |{{ site_settings.site_name  }}|
    {% else %}
        Портфолио
    {% endif %}

{% endblock %}


{% block content %}


<div class="page-hero">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="page-title">Портфолио.</h1>
                <p class="page-subtitle">Наши проекты, работы и достижения</p>
            </div>
        </div>
    </div>
</div>
<main class="main">
    <div class="container">
        <p class="page-subtitle">
            <div class="entry-meta">
                <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                <p class="entry-meta-item entry-comments-link">Портфолио</p>
            </div>
        </p>

        <div class="row">
            <div class="col-xl-9 col-lg-8 col-xs-12">

                {% include 'portfolio/includes/list_iter.html' %}

{#							<div class="paging"> <span>Page 3 of 4</span> <a href="">1</a> <a href="">2</a> <span class="current">3</span> <a href="">4</a> </div>#}

            </div>

            {% include 'portfolio/includes/right_column.html' %}


        </div>
    </div>
</main>





{% endblock %}

stroy_magaz/templates/portfolio/list_topic_portfolio.html
<style>
    .border {
        list-style: none;
        padding: 0;
    }
    .border li {
        font-family: "Trebuchet MS", "Lucida Sans";
        padding: 7px 20px;
        margin-bottom: 10px;
        border-radius: 5px;
        border-left: 10px solid #f05d22;
        box-shadow: 2px -2px 5px 0 rgba(0,0,0,.1),
        -2px -2px 5px 0 rgba(0,0,0,.1),
        2px 2px 5px 0 rgba(0,0,0,.1),
        -2px 2px 5px 0 rgba(0,0,0,.1);
        font-size: 20px;
        letter-spacing: 2px;
        transition: 0.3s all linear;
    }
    .border li:nth-child(2){border-color: #8bc63e;}
    .border li:nth-child(3){border-color: #fcba30;}
    .border li:nth-child(4){border-color: #1ccfc9;}
    .border li:nth-child(5){border-color: #493224;}
    .border li:hover {border-left: 10px solid transparent;}
    .border li:nth-child(1):hover {border-right: 10px solid #f05d22;}
    .border li:nth-child(2):hover {border-right: 10px solid #8bc63e;}
    .border li:nth-child(3):hover {border-right: 10px solid #fcba30;}
    .border li:nth-child(4):hover {border-right: 10px solid #1ccfc9;}
    .border li:nth-child(5):hover {border-right: 10px solid #493224;}
</style>
{% extends 'base.html' %}
{% load static %}


{%  block title %}

    Категория: {{ topic.name  }}

{% endblock %}


{% block content %}


    <div class="page-hero">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="page-title">Портфолио: {{ topic.name }}</h1>
                    <p class="page-subtitle">Наши проекты, работы и достижения</p>
                </div>
            </div>
        </div>
    </div>
    <main class="main">
        <div class="container">
            <p class="page-subtitle">
                <div class="entry-meta">
                    <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                    <p class="entry-meta-item entry-comments-link"><a href="{% url 'portfolio:list_all_portfolio' %}">Портфолио</a></p>
                    <p class="entry-meta-item entry-comments-link">{{ topic.name }}</p>
                </div>
            </p>

            <div class="row">
                <div class="col-xl-9 col-lg-8 col-xs-12">

                    {% include 'portfolio/includes/list_iter.html' %}

                    {% include 'portfolio/includes/right_column.html' %}

                </div>
            </div>
        </div>
    </main>





{% endblock %}

stroy_magaz/templates/portfolio/p_obj_detail.html
<style>
    .border {
        list-style: none;
        padding: 0;
    }
    .border li {
        font-family: "Trebuchet MS", "Lucida Sans";
        padding: 7px 20px;
        margin-bottom: 10px;
        border-radius: 5px;
        border-left: 10px solid #f05d22;
        box-shadow: 2px -2px 5px 0 rgba(0,0,0,.1),
        -2px -2px 5px 0 rgba(0,0,0,.1),
        2px 2px 5px 0 rgba(0,0,0,.1),
        -2px 2px 5px 0 rgba(0,0,0,.1);
        font-size: 20px;
        letter-spacing: 2px;
        transition: 0.3s all linear;
    }
    .border li:nth-child(2){border-color: #8bc63e;}
    .border li:nth-child(3){border-color: #fcba30;}
    .border li:nth-child(4){border-color: #1ccfc9;}
    .border li:nth-child(5){border-color: #493224;}
    .border li:hover {border-left: 10px solid transparent;}
    .border li:nth-child(1):hover {border-right: 10px solid #f05d22;}
    .border li:nth-child(2):hover {border-right: 10px solid #8bc63e;}
    .border li:nth-child(3):hover {border-right: 10px solid #fcba30;}
    .border li:nth-child(4):hover {border-right: 10px solid #1ccfc9;}
    .border li:nth-child(5):hover {border-right: 10px solid #493224;}
</style>
{% extends 'base.html' %}
{% load static %}


{%  block title %}

    Портфолио: {{ p_obj.name  }}

{% endblock %}



{% block content %}

    <div class="page-hero">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-title">{{ p_obj.name }}</h2>

                </div>
            </div>
        </div>
    </div>


    <main class="main">
        <div class="container">
            <p class="page-subtitle">
                <div class="entry-meta">
                    <p class="entry-meta-item entry-categories"><a href="{% url 'home_url' %}">Главная</a></p>
                    <p class="entry-meta-item entry-comments-link"><a href="{% url 'portfolio:list_all_portfolio' %}">Портфолио</a></p>
                    <p class="entry-meta-item entry-comments-link"><a href="{{ topic.get_absolute_url }}">{{ p_obj.topic }}</a></p>
                    <p class="entry-meta-item entry-comments-link">{{ p_obj.name }}</p>
                </div>
            </p>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-xs-12">
                    <article class="entry">
                        {% if p_obj.description %}
                            {{ p_obj.description|safe }}
                        {% else %}
                            <h4>Описание данной статьи еще не готово.</h4>
                            Для получение подробностей свяжитесь с нами.
                        {% endif %}

                        <br><br>
                        {% include 'portfolio/includes/gallery_p_obj.html' %}

                    </article>
                </div>

                {% include 'portfolio/includes/right_column.html' %}



            </div>




        </div>
    </main>
    {% include 'portfolio/includes/portfolio_comments.html' %}
{#    {% include 'portfolio/includes/gallery_p_obj.html' %}#}


{% endblock %}